# Generated by Django 4.0.1 on 2022-01-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('alert_rating', models.FloatField()),
                ('alert_g_spread', models.FloatField()),
                ('alert_bm_spread', models.FloatField()),
                ('alert_ai', models.FloatField()),
                ('alert', models.FloatField()),
                ('total', models.FloatField()),
                ('region', models.FloatField()),
            ],
        ),
    ]
