# Generated by Django 4.0.1 on 2022-01-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alert_history_update_at_alter_alert_history_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_history',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='blog/images/%Y/%m/%d'),
        ),
    ]
