# Generated by Django 4.0.1 on 2022-01-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alert_history_fild_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert_history',
            old_name='fild_upload',
            new_name='file_upload',
        ),
    ]
