# Generated by Django 4.0.1 on 2022-01-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_fild_upload_alert_history_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_history',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='alert_history',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
