# Generated by Django 4.0.1 on 2022-01-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_alert_history_file_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_history',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='blog/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='alert_history',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='blog/images/%Y/%m/%d'),
        ),
    ]
